### PR TITLE
Concepts link was not including end parenthesis

### PR DESCRIPTION
**Pull request by kristen-skydio**
Small change to use encoded character which appears to work. Sorry for the nit. It was misdirecting me to https://en.wikipedia.org/wiki/Concept_(generic_programming

### CODE REVIEW

**Review by aaron-skydio — APPROVED** [review]
Thanks - I bet it's a browser thing?  The current link in the [docs](https://symforce.org/tutorials/ops_tutorial.html) seems to work for me on chrome but I probably this works in strictly more places?

**Comment by aaron-skydio** [comment]
This actually seems to break the markdown handling in the generated docs?  Curious what environment you were seeing the broken link in 
image

**Comment by kristen-skydio** [comment]
I'm seeing it within github

There's a hanging closing parenthesis:
broken_link

And if you see the address of the link, it's missing it's closing parenthesis
broken_link_2

**Comment by aaron-skydio** [comment]
Huh, yep that's definitely wrong.  We might have to play around a bit to find something that works both on github and other notebook renderers and in the docs?  @bradley-solliday-skydio wanna take a look at this?

**Comment by aaron-skydio** [comment]
I think github must have fixed their markdown renderer so this is no longer necessary - this looks right to me now in both [the symforce docs](https://symforce.org/tutorials/ops_tutorial.html) and [github](https://github.com/symforce-org/symforce/blob/main/notebooks/tutorials/ops_tutorial.ipynb) on main

**Pull request closed without merging**
