### PR TITLE
Initialize default key contructor

### PR DESCRIPTION
**Pull request by simutisernestas**
Addressing #118, I suppose that was intended behavior : )

### CODE REVIEW

**Review by aaron-skydio — DISMISSED** [review]
Thanks!

**Comment by aaron-skydio** [comment]
This actually fails the assert in the main constructor:
```cpp
  Key(const char letter, const subscript_t sub, const superscript_t super)
      : letter_(letter), sub_(sub), super_(super) {
    SYM_ASSERT(letter != kInvalidLetter);
  }
```

I don't think we want to remove this assert, because indeed if you're passing a letter I think we should check that it's not invalid?  So I think

1) Maybe the best way to do this is to add defaults for those fields in the class, e.g. `char letter_{kInvalidLetter};`
2) We should add a test case to [`symforce_key_test`](https://github.com/symforce-org/symforce/blob/main/test/symforce_key_test.cc) that actually calls the default constructor, since apparently none of our existing symforce tests do

**Comment by simutisernestas** [comment]
@aaron-skydio do you have more test case ideas ?

**Review by aaron-skydio — APPROVED** [review]
That definitely covers it for this PR, coverage in that test is a little light so we could probably add more but no need for this PR imo

**Pull request closed without merging**
