### PR TITLE
Fix symengine_wrapper search

### LINKED ISSUE #330: error: can't copy 'build/temp.linux-x86_64-cpython-311/symengine_install/lib/python3.11/site-packages/symengine/lib/symengine_wrapper.cpython-311-x86_64-linux-gnu.so': doesn't exist or not a regular file
**Describe the bug**
The whole `build/temp.linux-x86_64-cpython-311/symengine_install/lib/python3.11` doesn't exist.

`find` shows that the file is are in 
`build/temp.linux-x86_64-cpython-311/symengine_install/local/lib/python3.11/dist-packages/symengine/lib/symengine_wrapper.cpython-311-x86_64-linux-gnu.so`

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. `python3 -m build -nwx .`

**Expected behavior**
Should be built.

**Environment (please complete the following information):**
 - OS and version: Debian sid
 - Python version 3.11
 - SymForce Version c3d2f3c97d77e8d9015276cd9ae7b080df646fc3

### PR DESCRIPTION
**Pull request by aaron-skydio**
So that it works on different platforms that e.g. use `local/lib` or
`site-packages`.

We were doing this correctly for editable installs but not non-editable
installs

Longer-term I'm leaning more and more towards requiring building
our copy of symengine separately first, but this is an easy strict
improvement for now

Fixes #330

Topic: sf-wrapper-glob
Reviewers: bradley,nathan,chao,ryan-b

### CODE REVIEW

**Comment by aaron-skydio** [comment]
Reviews in this chain:
└**https://github.com/symforce-org/symforce/pull/342** **Fix symengine_wrapper search**

**Comment by aaron-skydio** [comment]
| # | head | base | diff | date | summary |
| - | - | - | - | - | - |
| 0 | [5c892165](/symforce-org/symforce/commit/5c89216534a7b3eb651acd41408e84298d8f68d7) | [0940fa5b](/symforce-org/symforce/commit/0940fa5b25c3cff3efc57402fb4838bd8c96a5dc) | [diff](/symforce-org/symforce/compare/0940fa5b25c3cff3efc57402fb4838bd8c96a5dc..5c89216534a7b3eb651acd41408e84298d8f68d7) | Jun 2 13:04 PM |  1 file changed, 24 insertions(+), 13 deletions(-) |

**Comment by jieyeo-skymul** [comment]
Hi, I am still unable to build commit [71349254](https://github.com/symforce-org/symforce/commit/71349254666f9939f555f44104831011f951175a). 

I am on macOS Ventura 13.4 trying to install Symforce on a Ubuntu 22.04.2 virtual machine with the following:

Python 3.10.6
gcc 11.3.0
g++ 11.3.0
pip 23.1.2

The error seems to say:

file INSTALL cannot set permissions on "/usr/include": Operation not permitted.

Would you have any idea what the issue might be and how to fix it? I see the commit passed the CI/test-on-ubuntu (ubuntu-22.04, python3.10, gcc-11, g++-11) which seems to be the same as what I have so I'm not sure why I am running into an error.

**Comment by aaron-skydio** [comment]
That looks like #332 , I'm going to assume this fix works for #330

**Pull request closed without merging**
